services:
  tunnel:
    container_name: ngrok_tunnel
    image: ngrok/ngrok:latest
    restart: always
    command:
      - "http"
      - "--url=discourse-turbulent-abdominal.ngrok-free.dev"
      - "http://fintracker_app:5000"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_TOKEN}
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"