services:
  fintracker-bot:
    container_name: fintracker_app
    build: .
    restart: always
    volumes:
      - ./MyFinanceTracker.Host/appsettings.json:/app/appsettings.json
      - ./MyFinanceTracker.Host/secrets/google-api-credentials.json:/app/secrets/google-api-credentials.json
    environment:
      - TZ=Europe/Moscow
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"