services:
  fintracker-bot:
    container_name: fintracker_app
    image: ghcr.io/linnod/myfinancetracker:latest
    build: .
    restart: always
    environment:
      - TZ=Etc/UTC
      - DOTNET_ENVIRONMENT=Production
      - Telegram__Token=${TG_TOKEN}
      - Telegram__AllowedUserId=${TG_USER_ID}
      - GoogleSheets__SpreadsheetId=${GOOGLE_SHEET_ID}
      - GoogleSheets__CredentialsFilePath=/app/secrets/google-api-credentials.json
      - GoogleSheets__HeaderRowsCount=3
      - GoogleSheets__DecimalSeparator=,
      - YamlPersistence__FilePath=/app/data/categories.yaml
      - Interactions__EnableConsole=false
      - Interactions__EnableTelegram=true
    volumes:
      - ./deploy/google-api-credentials.json:/app/secrets/google-api-credentials.json:ro
      - ./deploy/categories.yaml:/app/data/categories.yaml:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"