namespace MyFinanceTracker.Interactions.Api.Extensions;

internal static class ApiEndpointsExtensions
{
    public static WebApplication MapApiEndpoints(this WebApplication app)
    {
        var api = app.MapGroup("/api");

        api.MapGet("/categories", ApiInteractionEndpoints.GetCategories)
           .WithName("GetCategories")
           .WithSummary("Get available categories and their aliases")
           .WithDescription("Call this BEFORE sending a transaction command to get the list of available categories and their valid aliases.");

        api.MapPost("/command", ApiInteractionEndpoints.ExecuteCommand)
           .WithName("ExecuteCommand")
           .WithSummary("Execute financial CLI command")
           .WithDescription("""
               Executes a financial CLI command generated by AI.
               
               Valid CLI Command Syntax:
               1. Add Expense Transaction:
                  - Standard: 't add expense <category_alias> <amounts> <date?> <note?>'
                    Example: 't add expense food 150'
                    Example: 't add expense taxi 50.5 20.01.2026 trip to office'
                  - Short syntax: 't + <category_alias> <amounts>'
                    Example: 't + food 150 200'

               2. Add Income Transaction:
                  - Standard: 't add income <category_alias?> <amounts> <date?> <note?>'
                    Example: 't add income salary 5000 01.02'
                    Example: 't add income 1000' (uses default income category)

               3. Clear Category Transactions for Date:
                  - Standard: 't rem <category_alias> <date>'
                    Example: 't rem food 20.01.2026'

               4. List All Categories:
                  - 'c all' or 'c list'
               """);

        return app;
    }
}