<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MyFinanceTracker.Infrastructure.GoogleSheets\MyFinanceTracker.Infrastructure.GoogleSheets.csproj" />
    <ProjectReference Include="..\MyFinanceTracker.Infrastructure.Persistence.Yaml\MyFinanceTracker.Infrastructure.Persistence.Yaml.csproj" />
    <ProjectReference Include="..\MyFinanceTracker.Interactions.Console\MyFinanceTracker.Interactions.Console.csproj" />
    <ProjectReference Include="..\MyFinanceTracker.Interactions.Telegram\MyFinanceTracker.Interactions.Telegram.csproj" />
    <ProjectReference Include="..\MyFinanceTracker.Interactions\MyFinanceTracker.Interactions.csproj" />
    <ProjectReference Include="..\MyFinanceTracker.Infrastructure.Persistence\MyFinanceTracker.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="..\MyFinanceTracker.UseCases\MyFinanceTracker.UseCases.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
  </ItemGroup>
  
  <ItemGroup>
    <None Update="appsettings.json" Condition="Exists('appsettings.json')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="categories.yaml" Condition="Exists('categories.yaml')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="google-api-credentials.json" Condition="Exists('google-api-credentials.json')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
